### ISSUE TITLE
feat: Having trouble plotting *points* representing facilities

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#22]
I am curious whether there is a way to plot color-coded **points** representing facilities using urbnmapr rather than color-coding counties or census tracts.

The CWNS dataset reports total wastewater flow for each facility, along with its latitude and longitude. I'd like to use this physical location data to plot a point for each facility and color-code it based on the amount of total flow to create a heatmap. However, I'd like to **overlay** these points over the urbnmapr states shapefile, so that we can tell in which state each point is located.

I can plot only the points (distorted, without a shapefile - see below), but as soon as I try to overlay this on the states shapefile, my code breaks. @atkissoncj Is this the right forum to post code when we encounter issues like this? 

<img width="897" alt="image" src="https://github.com/uwescience/WaterReuseDSSG2024/assets/152767057/aeb93988-1ce2-4490-a48a-a559750eb6e7">

**Comment by atkissoncj** [comment]
[See the urbnmapr documentation](https://github.com/UrbanInstitute/urbnmapr). It seems that this is based on something called fiftystater. My guess is that doesn't allow for non-states (e.g., Virgin Islands, Puerto Rico, etc.). The projection they use likely doesn't accommodate points so far away. When you do it without territories, does it work?

**Comment by atkissoncj** [comment]
>  @atkissoncj Is this the right forum to post code when we encounter issues like this?

Yes

**Comment by voglerdaniel** [comment]
> [See the urbnmapr documentation](https://github.com/UrbanInstitute/urbnmapr). It seems that this is based on something called fiftystater. My guess is that doesn't allow for non-states (e.g., Virgin Islands, Puerto Rico, etc.). The projection they use likely doesn't accommodate points so far away. When you do it without territories, does it work?

Thanks! Unfortunately filtering the data down to only the 50 US states does not resolve this issue. Output ends up looking like this:

![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/152767057/ab81b6c6-179f-4a8f-aea2-13fa8284bee2)

**Comment by atkissoncj** [comment]
But what if you map the reduced set without the shape file? Is that still distorted?

**Comment by voglerdaniel** [comment]
> But what if you map the reduced set without the shape file? Is that still distorted?

Not as bad, but ideally I'd like overlay it for consistency with other mappings.

![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/152767057/01d8f4e8-765a-4aeb-9a8c-a9205041aef4)

**Comment by atkissoncj** [comment]
And is urbnmapr really what we should be using? Aren't there known issues with urbnmapr?

**Comment by atkissoncj** [comment]
> Not as bad, but ideally I'd like overlay it for consistency with other mappings.

Yeah, sure, but at least it works.

**Comment by voglerdaniel** [comment]
> And is urbnmapr really what we should be using? Aren't there known issues with urbnmapr?

Agreed, I'm looking at alternatives for this. 

Another question you could ask is why we want to plot points in the first place, rather than summing flow over counties. The answer is that the county data in this file is a mess - 89% of the `COUNTY_FIPS` field is empty. We'd have to map each latitude and longitude to counties if we want to generate this map at a county level.

**Comment by atkissoncj** [comment]
@chayek Can you share code here (or point to the line) that will allow us to get points on a shapefile?

**Comment by atkissoncj** [comment]
Create function that allows you to take in points and the shape file level the user would like and creates a good, consistent map. @voglerdaniel : note that this has been made into a feature. Feel free to remove it as a feature if another feature already exists that will do this and note the feature that will close this concern.

**Comment by npovejsil** [comment]
Is this resolved by usmap package now?

**Comment by voglerdaniel** [comment]
The USMap package solved part of the problem - I can now overlay points on a states shapefile. But the distortion problem still exists:
![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/152767057/dcee351c-a11e-48d3-bfd4-233aa2e43d77)
@chayek and I are working on addressing it

**Comment by atkissoncj** [comment]
Is usmap the package that we'll be using? Or will we be building a different dependency?

**Comment by Jihyeonbae** [comment]
https://stackoverflow.com/questions/58676661/geom-sf-mapping-points-shapes
These steps helped me overlay points on external shape files (not urbnmpr).

**Comment by voglerdaniel** [comment]
Closing - this functionality will be covered by #24
